[conf]
default-lang = "en"

[lang.en]
aalto = "Aalto University"
sci = "School of Science"
program = "Bachelor's Programme in Science and Technology"
thesis = "Bachelor's thesis"
summary = "BACHELOR'S THESIS\nSUMMARY"
author = "Author"
title = "Thesis title"
date = "date"
nof_pages = "No. of pages"
major = "Major"
course_code = "Course code"
main_teacher = "Main teacher"
supervisor = "Supervisor"
keywords = "Keywords"
language = "Language"
appendix = "Appendix"
january = "January"
february = "February"
march = "March"
april = "April"
may = "May"
june = "June"
july = "July"
august = "August"
september = "September"
october = "October"
november = "November"
december = "December"

[lang.fi]
aalto = "Aalto-yliopisto"
sci = "Perustieteiden korkeakoulu"
program = "Teknistieteellinen kandidaattiohjelma"
thesis = "Kandidaattityö"
summary = "KANDIDAATTITYÖN\nTIIVISTELMÄ"
author = "Tekijä"
title = "Työn nimi"
date = "Päiväys"
nof_pages = "Sivumäärä"
major = "Pääaine"
course_code = "Koodi"
main_teacher = "Vastuuopettaja"
supervisor = "Työn ohjaaja"
keywords = "Avainsanat"
language = "Kieli"
appendix = "Liitteet"
january = "Tammikuuta"
february = "Helmikuuta"
march = "Maaliskuuta"
april = "Huhtikuuta"
may = "Toukokuuta"
june = "Kesäkuuta"
july = "Heinäkuuta"
august = "Elokuuta"
september = "Syyskuuta"
october = "Lokakuuta"
november = "Marraskuuta"
december = "Joulukuuta"
